server:
  port: 8089
spring:
  datasource:
      url: jdbc:mysql://rm-uf67658kxo1ooy26eo.mysql.rds.aliyuncs.com:3306
      username: root
      password: Zhongchongtao137
      driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 100MB