spring:
  datasource:
      url: jdbc:mysql://localhost:3306/postcardTailor
      username: root
      password: zhongchongtao137
      driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  activemq:
    broker-url: tcp://localhost:61616
soho:
  jms:
    activemq:
      queue-names:
        postcard_cropQueue: postCardQueue
  web:
    view-controllers:
      background: background/index
      background/postcard/tailor: background/postcard/postcard_crop
      background/settings/postcardSize: background/settings/size/size_show
      background/settings/cardBack: background/settings/cardback/cardback_show
      background/order/all: background/order/order_view
#    api-base-path: http://192.168.1.119:8100/api
#    file-base-path: http://192.168.1.119:8089/file